### ISSUE TITLE
Review config structure

### ISSUE THREAD

**Issue by richburdon** [dxos/dxos#3001]
## Notes

- Canonical (DMG) config for client, kube server, applications/bot/frame modules, etc.
- Canonical URNs for DMG (incl. DIDs)
- List of canonical ports
- Well-known endpoints (e.g., `.well-known/dx/config.json`)

We should really be using the term “signaling” over “signal”. Mykola pls determine if that’s a practical change otherwise don’t.

Second, .well-known should be endpoints for returning metadata file — not actual service endpoints. This is a much bigger change. E.g., each KUBE “web service” should have a corresponding well-known definition, that might have information about it’s service endpoints (we don’t need to do this now). However, the signaling server’s endpoint should nto be .well-klnown/dx/signal

I propose:
All `.well-known/dx` are “KUBE (web) services” (https://en.wikipedia.org/wiki/Well-known_URI) have “endpoints” (which are URIs by type); NOTE: these services may expose different APIs e.g., /ux, different ports, methods, etc.

The signaling server may also require more information later (https://meetrix.io/blog/webrtc/how-to-setup-a-signaling-server.html)

so:

```
services
  # https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling
  signaling
    server: 
      - url: wss://kube.dxos.org:7100 # TODO.

  # https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Protocols
  ice:
    - urls: turn:kube.dxos.org:3478
      username: dxos
```

NOTE: In my view `urls` should be `uris` but is so commonly used we should keep it.

I also encourage adding canonical reference links (W3C specs or MDN) comments if they are particularly helpful.
