### ISSUE TITLE
[telemetry] Internal Telemetry spec

### ISSUE THREAD

**Issue by mykola-vrmchk** [dxos/dxos#3491]
## Changes to config
```yml
version: 1

runtime:
  kube: 
    telemetry:
      tags: ['internal'] # Or we can generate a unique ID that we will share in org
```
- [x] Make apps talk to local Kube and check if it is internal Telemetry:
  - [x] Introduce internal telemetry tag in proto Config
  - [x] Make @dxos/telemetry request config endpoint of a local kube and tag telemetry events respectively
  - [ ] Do not show internal telemetry on dashboards
  - [ ] Add info about tags into the internal setup readme.md
